name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: restore build & cargo cache
        uses: Swatinem/rust-cache@v2

      - name: install clippy & rustfmt
        run: rustup components add clippy rustfmt

      - uses: jdx/mise-action@v3
        with:
          cache: true

      - run: just lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: restore build & cargo cache
        uses: Swatinem/rust-cache@v2

      - uses: jdx/mise-action@v3
        with:
          cache: true

      - run: just tests
